import Navigation from '../components/Navigation'
import About from '../components/About'
import Contact from '../components/Contact'
import Footer from '../components/Footer'

import type { NextPage } from 'next'
import Head from 'next/head'

import { Container } from '../styles/pages/home'

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
          <Navigation />
      </header>
      <main>
          <About />
          <Contact />
      </main>
      <Footer />
    </Container>
  )
}

export default Home
